### ISSUE TITLE
Translation widget isn't mobile friendly at all

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/l10n_client#5]
... but I have no idea, how this could get accomplished.

Fancy style mockups welcome! :smiley:

(BTW: this widget should get its own theme hook and template, which could be done together with a style overhaul.)

Update: And only 3 years later things get done. :speak_no_evil: 

TODO: update module screenshot after merge.

**Comment by indigoxela** [comment]
Still not ideal for _very_ narrow screens (phone...), but slightly better: instead of three columns, only two.
It makes no sense anyway, to waste so much space for vertical input fields, as the majority of translatable items' rather short.

![l10n-client-new-layout](https://github.com/backdrop-contrib/l10n_client/assets/842066/ea3a4517-e970-41cf-aa2e-82439fc6f550)

**Comment by indigoxela** [comment]
Added some media queries and belief, this is the best we can do... :wink: 

Testing, anyone?

**Comment by herbdool** [comment]
I've only looked at your screenshot above and compared to the screenshot here https://github.com/backdrop-contrib/l10n_client/blob/1.x-1.x/README.md. I think that's an improvement. That's two columns for all screen sizes? 

I don't think we're using this with any clients. I'm not sure why not, it would be helpful.

**Comment by indigoxela** [comment]
> That's two columns for all screen sizes?

On narrow screens it's just one. On wider two.

Initially I planned to make it three on wider screens, but quickly realized, that two - "Translation..." below "Source" is much nicer, anyway.

**Comment by indigoxela** [comment]
> I don't think we're using this with any clients. I'm not sure why not...

It's more like an admin-task to translate the interface, I guess. Neither content editors nor regular accounts usually do that, so... :shrug: :wink:

**Comment by herbdool** [comment]
Sounds good to me! When a client complains about the interface we'll install it.
